# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

- name: Setup Unity
  # You may pin to the exact commit or the version.
  # uses: kuler90/setup-unity@cfd7f2e4c3de6577a8776104278bcb0bf541173d
  uses: kuler90/setup-unity@v1.1.0
  with:
    # Unity version to install. For example, 2019.4.9f1. Project version will be used if not provided
    unity-version: 2022.2.16f1
    # Unity version changeset. For example, 50fe8a171dd9. Automatically parsed from Unity site if not provided
    unity-version-changeset: # optional
    # List of Unity modules (e.g. build support) to install. For example, [ios, android, webgl].


on:
  - workflow_dispatch
  label:
    types:
      - created

jobs:
  build:
- name: Setup Unity
  # You may pin to the exact commit or the version.
  # uses: kuler90/setup-unity@cfd7f2e4c3de6577a8776104278bcb0bf541173d
  uses: kuler90/setup-unity@v1.1.0
  with:
    unity-version: 2022.2.16f1

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 4.8.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
