- name: Setup Unity
  # You may pin to the exact commit or the version.
  # uses: kuler90/setup-unity@cfd7f2e4c3de6577a8776104278bcb0bf541173d
  uses: kuler90/setup-unity@v1.1.0
  with:
    # Unity version to install. For example, 2019.4.9f1. Project version will be used if not provided
    unity-version: 2022.2.16f1
    # Unity version changeset. For example, 50fe8a171dd9. Automatically parsed from Unity site if not provided
    unity-version-changeset: # optional
    # List of Unity modules (e.g. build support) to install. For example, [ios, android, webgl].

Available modules:
  Documentation: documentation
  Standard Assets: standardassets
  Example Project: example
  Android Build Support: android
  iOS Build Support: ios
  tvOS Build Support: appletv
  Linux Build Support: linux-mono
  SamsungTV Build Support: samsung
  Tizen Build Support: tizen
  WebGL Build Support: webgl
  Windows Build Support: windows
  Facebook Gameroom Build Support: facebook-games
  MonoDevelop / Unity Debugger: monodevelop
  Vuforia Augmented Reality Support: vuforia-ar
  Language packs: language-ja, language-ko, language-zh-cn, language-zh-hant, language-zh-hans
  Mac Build Support (IL2CPP): mac-il2cpp
  Windows Build Support (Mono): windows-mono
  Android SDK & NDK Tools: android-sdk-ndk-tools
  OpenJDK: android-open-jdk
  Lumin OS (Magic Leap) Build Support: lumin

  Also list of available modules can be checked by execute: `<path-to-unity-hub> -- --headless help`

    unity-modules: # optional
    # Automatically installs all child modules of selected modules. For example, android-open-jdk and android-sdk-ndk-tools for android
    unity-modules-child: # optional, default is true
    # Path to Unity project. Used to find Unity version
    project-path: # optional, default is ${{ github.workspace }}
    # Path where the Unity editor will be installed
    install-path: # optional
    # If true, avoid to invoke commands with sudo
    self-hosted: # optional
